# SPDX-License-Identifier: GPL-2.0

ccflags-y += -include $(src)/../../include/hamradio_compat.h

obj-m += rose.o

rose-y := af_rose.o rose_dev.o rose_in.o rose_link.o rose_loopback.o \
	  rose_out.o rose_route.o rose_subr.o rose_timer.o \
	  sysctl_net_rose.o
